# Generated by Django 3.2 on 2025-08-14 18:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=64)),
                ('vehicle_type', models.CharField(default='Standard', max_length=64)),
                ('mode', models.CharField(choices=[('METERED', 'Metered (Bolt/LagRide)'), ('NEGOTIATED', 'Negotiated (inDrive)')], default='METERED', max_length=16)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
                ('per_km', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=10)),
                ('per_min', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('min_fare', models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=256)),
                ('dropoff_address', models.CharField(max_length=256)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_amount_low', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_amount_high', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('INAPP', 'In‑App'), ('CASH', 'Cash')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], db_index=True, default='OPEN', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(default='Lagos', max_length=64)),
                ('vehicle_type', models.CharField(default='Standard', max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequestMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('distance_to_pickup_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('eta_to_pickup_min', models.PositiveSmallIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_request_matches', to='profiles.driver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ride.riderequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_request_matches', to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=256)),
                ('dropoff_address', models.CharField(max_length=256)),
                ('end_address', models.CharField(blank=True, default='', max_length=256)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_amount_low', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_amount_high', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('INAPP', 'In‑App'), ('CASH', 'Cash')], max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='REQUESTED', max_length=20)),
                ('city', models.CharField(default='Lagos', max_length=64)),
                ('vehicle_type', models.CharField(default='Standard', max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='profiles.driver')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rating.rating')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='vehicle.vehicle')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingconfig',
            index=models.Index(fields=['city'], name='ride_pricin_city_488d82_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingconfig',
            index=models.Index(fields=['vehicle_type'], name='ride_pricin_vehicle_8ba74e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingconfig',
            index=models.Index(fields=['active'], name='ride_pricin_active_096da3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingconfig',
            unique_together={('city', 'vehicle_type')},
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ride.riderequest'),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='riderequestmatch',
            index=models.Index(fields=['status'], name='ride_ridere_status_518a19_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequestmatch',
            index=models.Index(fields=['created_at'], name='ride_ridere_created_6c1aec_idx'),
        ),
        migrations.AddConstraint(
            model_name='riderequestmatch',
            constraint=models.UniqueConstraint(fields=('request', 'driver'), name='unique_request_driver'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status'], name='ride_ridere_status_abc5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['requested_at'], name='ride_ridere_request_698e06_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['customer', 'status'], name='ride_ridere_custome_0deffe_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['city'], name='ride_ridere_city_73ed73_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['vehicle_type'], name='ride_ridere_vehicle_17fa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='ride_ride_status_13d03a_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['requested_at'], name='ride_ride_request_d984eb_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='ride_ride_driver__7e0995_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['city'], name='ride_ride_city_701922_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['vehicle_type'], name='ride_ride_vehicle_1718e3_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationoffer',
            index=models.Index(fields=['role'], name='ride_negoti_role_6395e7_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationoffer',
            index=models.Index(fields=['created_at'], name='ride_negoti_created_eb8ac2_idx'),
        ),
    ]
